In [1]:
import sys
import os
import pandas as pd # Essencial para criar e manipular os DataFrames

# Adiciona o diretório raiz ao path para encontrar a pasta 'src'
sys.path.append('..')

In [2]:
from src.table_extractor import extract_raw_dataframe
from src.table_enhancer import enhance_table

In [3]:
# --- 2. DEFINIÇÃO DAS ENTRADAS DE TESTE (HARDCODED) ---
# Escolha um PDF e uma página específicos para o teste.
# Isso torna o teste repetível e fácil de depurar.
pdf_de_teste = '../data/input/Calendário Acadêmico pós greve veteranos.pdf' # Use o nome exato de um de seus arquivos
pagina_de_teste = 2 # Escolha uma página que VOCÊ SABE que tem uma tabela

In [4]:
print("Ambiente de teste pronto com funções refatoradas.")

pdf_de_teste = '../data/input/Calendário Acadêmico pós greve veteranos.pdf'
pagina_de_teste = 2

print(f"\nArquivo: {os.path.basename(pdf_de_teste)}, Página: {pagina_de_teste}")

print("\n--- PASSO 1: Extraindo DataFrame bruto... ---")
raw_df = extract_raw_dataframe(pdf_path=pdf_de_teste, page=pagina_de_teste)

if not raw_df.empty:
    print("✅ Sucesso! DataFrame bruto extraído. Veja abaixo:")
    display(raw_df)
    
    print("\n--- PASSO 2: Aprimorando a tabela... ---")
    enhanced_table_info = enhance_table(raw_df)
    
    if enhanced_table_info:
        print("✅ Sucesso! Tabela aprimorada.")
        print("\n--- RESULTADO FINAL ---")
        
        print("\n[Legenda Separada]")
        print(enhanced_table_info.get('legend'))
        
        print("\n[Tabela Limpa]")
        display(pd.DataFrame(enhanced_table_info.get("cleaned_table")))
        
        print("\n[Resumo Gerado]")
        print(enhanced_table_info.get("summary"))
    else:
        print("❌ Falha: O aprimoramento não retornou resultados.")
else:
    print("❌ Falha: Nenhuma tabela bruta foi extraída da página.")

Ambiente de teste pronto com funções refatoradas.

Arquivo: Calendário Acadêmico pós greve veteranos.pdf, Página: 2

--- PASSO 1: Extraindo DataFrame bruto... ---
✅ Sucesso! DataFrame bruto extraído. Veja abaixo:

C:\Users\lucas\AppData\Local\Programs\Python\Python313\Lib\site-packages\camelot\utils.py:1217: UserWarning:   (211.08000149999998, 211.21296669375) does not lie in column range (211.39692304538715, 385.36232811769446)
  warnings.warn(

                                                   0   1   2   3   4   5   6
0                           Julho - 23  Dias Letivos
1                                                  D   S   T   Q   Q   S   S
2                                                     01  02  03  04  05  06
3                                                 07  08  09  10  11  12  13
4                                                 14  15  16  17  18  19  20
5                                                 21  22  23  24  25  26  27
6                                                 28  29  30  31
7  01 – Retorno das aulas pós-greve \n03 – Feriad...

--- PASSO 2: Aprimorando a tabela... ---
✅ Sucesso! Tabela aprimorada.

--- RESULTADO FINAL ---

[Legenda Separada]
01 – Retorno das aulas pós-greve  03 – Feriado Municipal – Aniversário da cidade de   Montes Claros;  13 – Sábado letivo presencial referente à Quarta- feira

[Tabela Limpa]

    D   S   T   Q Q_2 S_2 S_3
0      01  02  03  04  05  06
1  07  08  09  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31

[Resumo Gerado]
A tabela 'Julho - 23  Dias Letivos' descreve um calendário. A legenda informa: '01 – Retorno das aulas pós-greve  03 – Feriado Municipal – Aniversário da cidade de   Montes Claros;  13 – Sábado letivo presencial referente à Quarta- feira'. Detalhes do calendário: na semana 1, dia S é 01, dia T é 02, dia Q é 03, dia Q é 04, dia S é 05, dia S é 06; na semana 2, dia D é 07, dia S é 08, dia T é 09, dia Q é 10, dia Q é 11, dia S é 12, dia S é 13; na semana 3, dia D é 14, dia S é 15, dia T é 16, dia Q é 17, dia Q é 18, dia S é 19, dia S é 20; na semana 4, dia D é 21, dia S é 22, dia T é 23, dia Q é 24, dia Q é 25, dia S é 26, dia S é 27; na semana 5, dia D é 28, dia S é 29, dia T é 30, dia Q é 31.